/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as CartoesRouteImport } from './routes/cartoes'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as ContasRouteImport } from './routes/contas'
import { Route as DividasRouteImport } from './routes/dividas'
import { Route as InvestimentosRouteImport } from './routes/investimentos'
import { Route as MetasRouteImport } from './routes/metas'
import { Route as OrcamentosRouteImport } from './routes/orcamentos'
import { Route as PatrimonioRouteImport } from './routes/patrimonio'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as TransacoesRouteImport } from './routes/transacoes'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const CartoesRoute = CartoesRouteImport.update({
  id: '/cartoes',
  path: '/cartoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ContasRoute = ContasRouteImport.update({
  id: '/contas',
  path: '/contas',
  getParentRoute: () => rootRouteImport,
} as any)
const DividasRoute = DividasRouteImport.update({
  id: '/dividas',
  path: '/dividas',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestimentosRoute = InvestimentosRouteImport.update({
  id: '/investimentos',
  path: '/investimentos',
  getParentRoute: () => rootRouteImport,
} as any)
const MetasRoute = MetasRouteImport.update({
  id: '/metas',
  path: '/metas',
  getParentRoute: () => rootRouteImport,
} as any)
const OrcamentosRoute = OrcamentosRouteImport.update({
  id: '/orcamentos',
  path: '/orcamentos',
  getParentRoute: () => rootRouteImport,
} as any)
const PatrimonioRoute = PatrimonioRouteImport.update({
  id: '/patrimonio',
  path: '/patrimonio',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const TransacoesRoute = TransacoesRouteImport.update({
  id: '/transacoes',
  path: '/transacoes',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/cartoes': typeof CartoesRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/contas': typeof ContasRoute
  '/dividas': typeof DividasRoute
  '/investimentos': typeof InvestimentosRoute
  '/metas': typeof MetasRoute
  '/orcamentos': typeof OrcamentosRoute
  '/patrimonio': typeof PatrimonioRoute
  '/relatorios': typeof RelatoriosRoute
  '/transacoes': typeof TransacoesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/cartoes': typeof CartoesRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/contas': typeof ContasRoute
  '/dividas': typeof DividasRoute
  '/investimentos': typeof InvestimentosRoute
  '/metas': typeof MetasRoute
  '/orcamentos': typeof OrcamentosRoute
  '/patrimonio': typeof PatrimonioRoute
  '/relatorios': typeof RelatoriosRoute
  '/transacoes': typeof TransacoesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/cartoes': typeof CartoesRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/contas': typeof ContasRoute
  '/dividas': typeof DividasRoute
  '/investimentos': typeof InvestimentosRoute
  '/metas': typeof MetasRoute
  '/orcamentos': typeof OrcamentosRoute
  '/patrimonio': typeof PatrimonioRoute
  '/relatorios': typeof RelatoriosRoute
  '/transacoes': typeof TransacoesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agenda'
    | '/cartoes'
    | '/configuracoes'
    | '/contas'
    | '/dividas'
    | '/investimentos'
    | '/metas'
    | '/orcamentos'
    | '/patrimonio'
    | '/relatorios'
    | '/transacoes'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agenda'
    | '/cartoes'
    | '/configuracoes'
    | '/contas'
    | '/dividas'
    | '/investimentos'
    | '/metas'
    | '/orcamentos'
    | '/patrimonio'
    | '/relatorios'
    | '/transacoes'
  id:
    | '__root__'
    | '/'
    | '/agenda'
    | '/cartoes'
    | '/configuracoes'
    | '/contas'
    | '/dividas'
    | '/investimentos'
    | '/metas'
    | '/orcamentos'
    | '/patrimonio'
    | '/relatorios'
    | '/transacoes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgendaRoute: typeof AgendaRoute
  CartoesRoute: typeof CartoesRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  ContasRoute: typeof ContasRoute
  DividasRoute: typeof DividasRoute
  InvestimentosRoute: typeof InvestimentosRoute
  MetasRoute: typeof MetasRoute
  OrcamentosRoute: typeof OrcamentosRoute
  PatrimonioRoute: typeof PatrimonioRoute
  RelatoriosRoute: typeof RelatoriosRoute
  TransacoesRoute: typeof TransacoesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cartoes': {
      id: '/cartoes'
      path: '/cartoes'
      fullPath: '/cartoes'
      preLoaderRoute: typeof CartoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contas': {
      id: '/contas'
      path: '/contas'
      fullPath: '/contas'
      preLoaderRoute: typeof ContasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dividas': {
      id: '/dividas'
      path: '/dividas'
      fullPath: '/dividas'
      preLoaderRoute: typeof DividasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investimentos': {
      id: '/investimentos'
      path: '/investimentos'
      fullPath: '/investimentos'
      preLoaderRoute: typeof InvestimentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metas': {
      id: '/metas'
      path: '/metas'
      fullPath: '/metas'
      preLoaderRoute: typeof MetasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orcamentos': {
      id: '/orcamentos'
      path: '/orcamentos'
      fullPath: '/orcamentos'
      preLoaderRoute: typeof OrcamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patrimonio': {
      id: '/patrimonio'
      path: '/patrimonio'
      fullPath: '/patrimonio'
      preLoaderRoute: typeof PatrimonioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transacoes': {
      id: '/transacoes'
      path: '/transacoes'
      fullPath: '/transacoes'
      preLoaderRoute: typeof TransacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgendaRoute: AgendaRoute,
  CartoesRoute: CartoesRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  ContasRoute: ContasRoute,
  DividasRoute: DividasRoute,
  InvestimentosRoute: InvestimentosRoute,
  MetasRoute: MetasRoute,
  OrcamentosRoute: OrcamentosRoute,
  PatrimonioRoute: PatrimonioRoute,
  RelatoriosRoute: RelatoriosRoute,
  TransacoesRoute: TransacoesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
